#!/usr/bin/env python

import sys

from rqt_thump.user_study import UserStudyPlugin
from rqt_gui.main import Main

plugin = 'rqt_thump'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))